In [2]:
import pandas as pd
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pylab
import math
from scipy import stats
from sklearn import preprocessing
import statsmodels.api as sm
from statsmodels.stats import diagnostic as diag
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn import metrics

%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
from scipy.io import loadmat
import os
from scipy.optimize import fmin_cg
import scipy.io
import scipy.io as si

In [3]:
#Stack arrays in sequence horizontally (column wise).
np.hstack

<function numpy.hstack(tup)>

In [4]:
#Return a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye

<function numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')>

In [5]:
# np.roll Roll (move in a particular direction) array elements along a given axis.
np.roll

<function numpy.roll(a, shift, axis=None)>

# Index selection from numpy

In [6]:
y =np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [7]:
y[1:5:2,::3]

array([[ 7, 10, 13],
       [21, 24, 27]])

In [8]:
y[:2,:3]

array([[0, 1, 2],
       [7, 8, 9]])

In [9]:
y[:,:3]

array([[ 0,  1,  2],
       [ 7,  8,  9],
       [14, 15, 16],
       [21, 22, 23],
       [28, 29, 30]])

In [10]:
y[:,2:3]

array([[ 2],
       [ 9],
       [16],
       [23],
       [30]])

In [11]:
#size inja 5*1
y[:,6:7]

array([[ 6],
       [13],
       [20],
       [27],
       [34]])

In [12]:
#size array ba balai fargh dare, 1*5
y[:,6]

array([ 6, 13, 20, 27, 34])


# Index selection from pandas

In [13]:
dates = pd.date_range('1/1/2000', periods=8)

In [14]:
df = pd.DataFrame(np.random.randn(8, 4),index=dates, columns=['A', 'B', 'C', 'D'])

In [15]:
df

A         B         C         D
2000-01-01 -0.564622 -1.256865  1.164137  1.796757
2000-01-02 -1.928502 -0.363082 -0.369308 -0.992491
2000-01-03 -0.991083 -1.031794 -0.814554  1.225768
2000-01-04 -1.561099 -0.388830  0.261078  1.051546
2000-01-05  0.392431 -1.939818  1.704567  0.761374
2000-01-06 -0.958794  0.716762  1.475638 -0.178705
2000-01-07 -1.797081 -2.587660  0.005296 -0.468397
2000-01-08  1.844800 -0.828442 -1.065095  0.324969

In [16]:
#age esm column nayad fagaht satr manzur has
df[:3]

A         B         C         D
2000-01-01 -0.564622 -1.256865  1.164137  1.796757
2000-01-02 -1.928502 -0.363082 -0.369308 -0.992491
2000-01-03 -0.991083 -1.031794 -0.814554  1.225768

In [17]:
#vaghti :: miad yani tarz entekhab kardan
df[::2]

A         B         C         D
2000-01-01 -0.564622 -1.256865  1.164137  1.796757
2000-01-03 -0.991083 -1.031794 -0.814554  1.225768
2000-01-05  0.392431 -1.939818  1.704567  0.761374
2000-01-07 -1.797081 -2.587660  0.005296 -0.468397

In [18]:
 df['A'][1:3]

2000-01-02   -1.928502
2000-01-03   -0.991083
Freq: D, Name: A, dtype: float64

In [19]:
df['A'][:5]

2000-01-01   -0.564622
2000-01-02   -1.928502
2000-01-03   -0.991083
2000-01-04   -1.561099
2000-01-05    0.392431
Freq: D, Name: A, dtype: float64

In [19]:
df[::-1]

A         B         C         D
2000-01-08  0.032031  0.041630 -0.549961 -0.334102
2000-01-07  0.327321 -0.317337 -0.611482  0.357551
2000-01-06  0.967509  1.290951  0.642981  0.190391
2000-01-05  0.794173  1.308347 -0.405706  0.455019
2000-01-04  1.111303 -1.426620 -1.211976  0.475289
2000-01-03 -0.850196  0.482828  0.223072  0.630910
2000-01-02 -0.379168 -0.630180 -1.043777  1.778574
2000-01-01 -1.684100  0.949063  1.567990 -0.079819

# Resize numpy arange

In [20]:
a=np.arange(-100,100,0.1)
y=np.resize(a,(569))
y.shape

(569,)

# Assign empty list
### create an empty list and append items to it

In [21]:
#with append
sample_list = []
for i in range(10):
    sample_list.append(i)

In [22]:
sample_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
num = []
for i in range(3, 15, 2):
    num.append(i)
num

[3, 5, 7, 9, 11, 13]

In [24]:
#or with insert
sample_list = []
for i in range(10):
    sample_list.insert(len(sample_list), i)
sample_list 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# Assign empty array
### create an empty array and append items to it

In [25]:
sample= np.array([])
for n in  np.arange(5):
    value = (n + 1)*3
    sample = np.append(sample , value)

In [26]:
sample

array([ 3.,  6.,  9., 12., 15.])

==========================================
# What does *args and **kwargs do in the function definition
### *args and **kwargs allow you to pass multiple arguments or keyword arguments to a function. 

In [27]:
def my_sum(a, b):
    return a + b

### This function works fine, but it’s limited to only two arguments. What if you need to sum a varying number of arguments

### *kwargs works just like *args instead of accepting positional arguments it accepts keyword (or named) arguments. 

In [28]:
def concatenate(**kwargs):
    result = ""
    # Iterating over the Python kwargs dictionary
    for arg in kwargs.values():
        result += arg
    return result

print(concatenate(a="Real", b="Python", c="Is", d="Great", e="!"))

RealPythonIsGreat!


In [29]:
def drawLine(p1, p2, *args, **kwargs):
    
    plt.plot([p1[0], p2[0]], [p1[1], p2[1]], *args, **kwargs)

# Dimentionality Reduction
### np.linalg.svd is finding eigenvector and eighenvalues of a matrix (hear we look for eigenvallues and eigenvector of covariance matrix of the data). The bigger eigenvalue which lead to bigger eigenvector is our PCA.


In [30]:
# u is one eigenvector and v is the second. but we choose the biger one for PCA
#u, s, v = np.linalg.svd()
#u,s = pca(X_norm)

### There are differetn ways to find eigenvalues and vector in python:

In [31]:
Cov =np.array([[1.8,1.2],[4.4,4.6]])

In [32]:
values,vectors=np.linalg.eig(Cov.T*Cov)
vectors

array([[-0.96476382, -0.26311741],
       [ 0.26311741, -0.96476382]])

In [33]:
values

array([ 1.8, 22.6])

remeber that the eigenvector and values from the latter might be different in rows or columns. better to go with svd

### example 2, the result are correct (taken from exersize). the give same result but row and columsn are different and should be taken care of.

In [34]:
C = np.matrix([[5,5],[-1,7]])
C

matrix([[ 5,  5],
        [-1,  7]])

In [35]:
#should be normalized 
C.T*C

matrix([[26, 18],
        [18, 74]])

In [36]:
w, v = np.linalg.eig(C.T*C)
v

matrix([[-0.9486833 , -0.31622777],
        [ 0.31622777, -0.9486833 ]])

In [37]:
w

array([20., 80.])

In [38]:
u, s, vh = np.linalg.svd(C)
vh

matrix([[ 0.31622777,  0.9486833 ],
        [ 0.9486833 , -0.31622777]])

In [39]:
u

matrix([[ 0.70710678,  0.70710678],
        [ 0.70710678, -0.70710678]])

In [40]:
s**2

array([80., 20.])

# pass statement
#### The pass statement is used as a placeholder for future code. When the pass statement is executed, nothing happens, but you avoid getting an error when empty code is not allowed.

In [41]:
# when it reaches 'h' does not do anything
for letter in 'Python': 
   if letter == 'h':
      pass
      print('This is pass block')
   print('Current Letter :', letter)

print("Good bye!")

Current Letter : P
Current Letter : y
Current Letter : t
This is pass block
Current Letter : h
Current Letter : o
Current Letter : n
Good bye!


# Print

In [42]:
name ='giacomo'
number = 4.3
print('%s %s' % (name, number))

giacomo 4.3


In [43]:
name ='giacomo'
number = 4.3
print('number {}'.format(name)) 

number giacomo


# Some more

In [44]:
len('Hello World')

11

In [45]:
s='hello world'
s[0]

'h'

In [46]:
s[:]

'hello world'

In [47]:
s[::2]

'hlowrd'

In [48]:
s.split()

['hello', 'world']

In [49]:
s.split()[1]

'world'

In [50]:
s + ' concatenate me!'

'hello world concatenate me!'

In [51]:
my_list = ['one','two','three',4,5]

In [52]:
my_list + ['new item']

['one', 'two', 'three', 4, 5, 'new item']

In [53]:
list1 = [1,2,3]

In [54]:
# append is in-place for list, meaning that it does not return asigned name but the initual name, here list1
# nokte: inja nemituni be paini assign koni chizi, dobare bayad list1 ro seda koni
list1.append('append me!')
list1

[1, 2, 3, 'append me!']

In [55]:
#extend is in-place
x = [1, 2, 3]
y = [4, 5, 6]
x.extend(y)
print(x)

[1, 2, 3, 4, 5, 6]


In [56]:
mylist = ['a', 'b', 'b', 'c']
mylist.index('b')

1

In [57]:
mylist.index('c')

3

In [58]:
matrix=[[6, 2, 3], [4, 5, 6], [7, 8, 9]]

In [59]:
matrix[0][0]

6

# Input

In [60]:
# get input from user

inputString = input()

print('The inputted string is:', inputString)

1
The inputted string is: 1


In [61]:
# get input from user

inputString = input('Enter a string:')

print('The inputted string is:', inputString)

Enter a string:2
The inputted string is: 2


In [62]:
 input('go one')

go one


''

# Dictionary

In [63]:
my_dict = {'key1':'value1','key2':'value2'}

In [64]:

my_dict['key2']

'value2'

In [65]:
my_dict1 = {'key1':123,'key2':[12,23,33],'key3':['item0','item1','item2']}

In [66]:
my_dict1['key3']

['item0', 'item1', 'item2']

In [67]:
my_dict1['key3'][0]

'item0'

In [68]:
my_dict1['key1'] = my_dict1['key1'] - 123

In [69]:
my_dict1['key1']

0

# Tuple

In [70]:
t = ('one',2)

In [71]:
t[0]

'one'

In [72]:
t[-1]

2

# Set
### collection of unique elements

In [73]:
list1 = [1,1,2,2,3,4,5,6,1,1,10]

In [74]:
set(list1)

{1, 2, 3, 4, 5, 6, 10}

In [75]:
x = set()

In [76]:
x.add(1)

In [77]:
x

{1}

In [78]:
x.add(2)

In [79]:
x

{1, 2}

In [80]:
list5 = [1,2,2,33,4,4,11,22,3,3,2]

In [81]:
x = set(list5 )

In [82]:
x

{1, 2, 3, 4, 11, 22, 33}

# For loop

In [83]:
st = 'Print only the words that start with s in this sentence'

In [84]:
for i in st.split():
    if i[0] == 's':
        print(i)

start
s
sentence


In [85]:
list(range(0,11,2))

[0, 2, 4, 6, 8, 10]

### Write a program that prints the integers from 1 to 100. But for multiples of three print "Fizz" instead of the number, and for the multiples of five print "Buzz". For numbers which are multiples of both three and five print "FizzBuzz".

In [86]:
for num in range(1,16):
    if num % 3 == 0 and num % 5 == 0:
        print("FizzBuzz")
    elif num % 3 == 0:
        print("Fizz")
    elif num % 5 == 0:
        print("Buzz")
    else:
        print(num)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz


# If statement

In [87]:
loc = 'Bank'

if loc == 'Auto Shop':
    print('Welcome to the Auto Shop!')
elif loc == 'Bank':
    print('Welcome to the bank!')
else:
    print('Where are you?')

Welcome to the bank!


### print only the even numbers from this list, if not print 'odd number'

In [88]:
list1 = [1,2,3,4,5,6,7,8,9,10]

In [89]:
for num in list1:
    if num % 2 == 0:
        print(num)
    else:
        print('Odd number')

Odd number
2
Odd number
4
Odd number
6
Odd number
8
Odd number
10


# while statement

In [90]:
x = 0

while x < 5:
    print('x is currently: ',x)
    print(' x is still less than 10, adding 1 to x')
    x+=1

x is currently:  0
 x is still less than 10, adding 1 to x
x is currently:  1
 x is still less than 10, adding 1 to x
x is currently:  2
 x is still less than 10, adding 1 to x
x is currently:  3
 x is still less than 10, adding 1 to x
x is currently:  4
 x is still less than 10, adding 1 to x


In [91]:
x = 0

while x < 5:
    print('x is currently: ',x)
    print(' x is still less than 10, adding 1 to x')
    x+=1
    if x==3:
        print('x==3')
    else:
        print('continuing...')
        continue

x is currently:  0
 x is still less than 10, adding 1 to x
continuing...
x is currently:  1
 x is still less than 10, adding 1 to x
continuing...
x is currently:  2
 x is still less than 10, adding 1 to x
x==3
x is currently:  3
 x is still less than 10, adding 1 to x
continuing...
x is currently:  4
 x is still less than 10, adding 1 to x
continuing...


In [92]:
x = 0

while x < 10:
    print('x is currently: ',x)
    print(' x is still less than 10, adding 1 to x')
    x+=1
    if x==3:
        print('Breaking because x==3')
        break
    else:
        print('continuing...')
        continue

x is currently:  0
 x is still less than 10, adding 1 to x
continuing...
x is currently:  1
 x is still less than 10, adding 1 to x
continuing...
x is currently:  2
 x is still less than 10, adding 1 to x
Breaking because x==3


# Function interactions

In [93]:
example=[1,5,4]

In [94]:
from random import shuffle

In [95]:
#it is in-place,it does not return 'result' but the intial name which is example
result=shuffle(example)

In [96]:
example

[5, 1, 4]

In [97]:
# vali ba tarif function mitunim hala ye esmi assign konim be shuffle.
def shuffle_l(mylist):
    shuffle(mylist)
    return mylist

In [98]:
g=shuffle_l(example)
g

[1, 5, 4]

In [99]:
# game list looks like:user guess where is 'o'
mylist=[' ', 'o', ' ']

In [100]:
shuffle_l(mylist)

[' ', ' ', 'o']

In [101]:
# below why 0,1,2 are written as string, becuase input always returns string
def player_guess():
    guess=''
    
    while guess not in ['0','1','2']:
        guess=input('pick a number :0,1 or 2')
    return int(guess)
    
    

In [122]:
player_guess()

pick a number :0,1 or 22


2

In [123]:
#below is interaction betwee two latter functions
def check_guess(mylist, guess):
    if mylist[guess]== 'o':
        print('correct')
    else:
        print('wrong guess')

In [124]:
mylist=['','o','']
guess=player_guess()
check_guess(mylist, guess)

pick a number :0,1 or 23
pick a number :0,1 or 22
wrong guess


# Functions

### Write a function that returns the lesser of two given numbers if both numbers are even, but returns the greater if one or both numbers are odd

In [125]:
def lesser_of_two_evens(a,b):
    if a%2 == 0 and b%2 == 0:
        return min(a,b)
    else:
        return max(a,b)

In [126]:
lesser_of_two_evens(2,4)

2

### Write a function takes a two-word string and returns True if both words begin with same letter

In [127]:
def animal_crackers(text):
    wordlist = text.split()
    return wordlist[0][0] == wordlist[1][0]

In [128]:
animal_crackers('Levelheaded Llama')

True

### Given a list of ints, return True if the array contains a 3 next to a 3 somewehe

In [129]:
#method 1. Note the place of last return, it does not inside the for loop. so the for loops finishes over all i then goes to the last return.
def f(num):
    for i in range(0,len(num)-1):
        if num[i]==3 and num[i+1]==3:
            return True
    
    return False

In [130]:
f([1,3,5,3,3])

True

In [131]:
len([1,3,5,3,3])-1

4

In [132]:
#method 2
def f(num):
    for i in range(0,len(num)-1):
        if num[i:i+2]==[3,3]:
            return True
    return False

In [133]:
f([1,3,5,3])

False

### given a string, return a string where for every charachter in the original there are three character, e.g. Hello ---> HHHeeellllllooo

In [134]:
import numpy as np
def D(text):
    t=''
    for i in range(0,len(text)):
        t+=text[i]*3
    return t

In [135]:
D('text')

'ttteeexxxttt'

In [136]:
t=('tk')
t[1]*3

'kkk'

In [137]:
# note: .append does not work for strings, instead always try this
t=''
t += "lwrewr" 
t

'lwrewr'

### given three integers between 1 and 11, if their sum is less that or equl to 21, return their sum. If therie sum exceeds 21 and there is an eleven, redunce the total sum by 10. Finally if the sum (even after adjusment) excees 21, retunr 'BUST

In [138]:
#method1
def f(a,b,c):
    g=(a,b,c)
    if sum(g) <= 21:
        return sum(g)
    if sum(g) > 21 and b==11 or a==11 or c==11:
        return sum(g)-10
    if sum(g) > 21:
        return 'BUST'

In [139]:
f(15,9,6)


'BUST'

In [146]:
#method1
def f(a,b,c):
    if sum([a,b,c]) <= 21:
        return sum([a,b,c])
    elif sum([a,b,c])  > 21 and b==11 or a==11 or c==11:
        return sum([a,b,c])-10
    else:
        sum([a,b,c])  > 21
        return 'BUST'

In [147]:
f(15,9,6)

'BUST'

In [150]:
# note the first one does not work, should do the second
#sum(a,b,c)
#sum([a,b,c])

In [151]:
g=(5,6,7)
sum([5,6,7])

18

### return the sum of the numbers in the array, except ignore sections of numbers starting with a 6 and extending to the next 9 (every 6 will be followed by at least one 9). Return 0 for no numbers.

In [152]:
def f(num):
    sum=0
    for i in range(0,len(num)):
        sum += num[i]
    return sum

In [153]:
f([5,6,9])

20

In [268]:
###AGAIN, note to the last RETURN how it is written. we do no have else 
def f(num):
    for i in range(0,len(num)):
        for j in range(i+1,len(num)):
            if num[i]==6 and num[j]==9:
                d=num.index(6)
                h=num[:d]
                return sum(h)
    return sum(num)

In [269]:
f([12,2,6,9,11])


14

In [270]:
f=[5,6,9]

In [271]:
f.index(6)

1

In [272]:
sum(f[1:3])

15

In [273]:
g=[5,6,9]
g.index(6)

1

### Write a function that takes in a list of integers and returns 2 if it contains 0, otherwise return the list own components 

In [63]:
def fae(num):
    t=[]
    for i in  range(0,len(num)):
        if num[i]==0:
            t.append(2)
        else:
            t.append(num[i])
    return t

In [64]:
m=([12,0,0,0,7])

In [65]:
fae(m)

[12, 2, 2, 2, 7]

### Write a function that takes in a list of integers and returns 2 if it contains 0, otherwise return the list own components plus 3

In [68]:
def fae(num):
    t=[]
    for i in  range(0,len(num)):
        if num[i]==0:
            t.append(2)
        else:
            t.append(num[i]+3)
    return t

In [69]:
m=([12,0,0,0,7])
fae(m)

[15, 2, 2, 2, 10]

# Map and Filter
### The map method is used to convert each item of an array, while the filter method is used to select certain items of an array, or creates a new list with only those items that cause the function to return True.

In [9]:
def check_even(num):
    return num%2==0

In [10]:
mynums=[12,3,2,5,7]
list(filter(check_even,mynums))

[12, 2]

In [12]:
for n in filter(check_even,mynums):
    print(n)

12
2


# Convert tuple to  list 

In [2]:
aTuple = (123, 'xyz', 'zara', 'abc');
aList = list(aTuple)
print(aList)

[123, 'xyz', 'zara', 'abc']


## Join

In [163]:
list=['a','c','v']

In [164]:
''.join(list)

'acv'

In [165]:
'  '.join(list)

'a  c  v'

In [166]:
330*29000


9570000

# Nested statement and Scope

In [25]:
name = 'Ali'

def greet():
    name = 'sam'
    
    def hello():
        print('Hello ' + name)
        
    hello()
    
greet()

Hello sam


In [26]:
name = 'Ali'

def greet():
    name = 'sam'
    
    def hello():
        name = 'anna'
        print('Hello ' + name)
        
    hello()
    
greet()

Hello anna


In [27]:
name = 'Ali'

def greet():
    
    def hello():
        print('Hello ' + name)
        
    hello()
    
greet()

Hello Ali


In [35]:
x=50
def fun(x):
    print(f'x is {x}')
    
    x=200
    print(f'I is now {x}')

In [33]:
fun(x)

x is 50
I is now 200


### The following example shows defining global x inside fun impacs on the outside x (beginning). Note that fun() has no variable inside

In [52]:
x=50
def fun():
    global x
    print(f'you see now x is {x*2}')
    
    x=200
    print(f'I changed x golablly now {x}')

In [53]:
print(x)

50


In [54]:
fun()

you see now x is 100
I changed x golablly now 200


In [58]:
# another method similar to latter is to say with return
x=50
def fun():
    global x
    print(f'you see now x is {x*2}')
    
    x=200
    print(f'I changed x golablly now {x}')

In [59]:
print(x)

50


In [60]:
fun()

you see now x is 100
I changed x golablly now 200


# Lambda expression

In [23]:
doubler = lambda x: x*2

print(doubler(2))

4


In [24]:
# A lambda function that multiplies two values
mul = lambda x, y: x*y
print(mul(2, 5))

10


### With map()

In [25]:
# Double each item of the list
def doubler(x):
    return x*2

L = [1, 2, 3, 4, 5, 6]
mod_list = map(doubler, L)
print(list(mod_list))

[2, 4, 6, 8, 10, 12]


In [26]:
def checkAge(age):
    if age > 18:
        return True
    else:
        return False

age = [5, 11, 16, 19, 24, 42]
adults = filter(checkAge, age)
print(list(adults))

[19, 24, 42]


In [27]:
findSquareCube = lambda num: (num**2, num**3)
x, y = findSquareCube(2)
print(x)


4


In [28]:
print(y)

8


### if else in a Lambda

In [29]:
findMin = lambda x, y: x if x < y else y

print(findMin(2, 4))

2


In [30]:
print(findMin('a', 'x'))

a


# Functions and Methods
**Write a function that computes the volume of a sphere given its radius.**
<p>The volume of a sphere is given as $$\frac{4}{3} πr^3$$</p>

In [48]:
import math
volume = lambda radius :  4/3* math.pi*radius**3

volume(5)

523.5987755982989

**Write a function that checks whether a number is in a given range (inclusive of high and low)**

In [1]:
def fun(num):
    if num in range(0,10):
        return True
    else:
        return False

In [3]:
num=5
fun(50)

False

**Write a Python function that accepts a string and calculates the number of upper case letters and lower case letters.**

    Sample String : 'Hello Mr. Rogers, how are you this fine Tuesday?'
    Expected Output : 
    No. of Upper case characters : 4
    No. of Lower case Characters : 33

HINT: Two string methods that might prove useful: **.isupper()** and **.islower()**

In [142]:
def fun(text):
    t=0
    z=0
    for i in range(0, len(text)-1):
        if text[i].upper()==text[i]:
            t += 1
        elif text[i].lower()==text[i]:
            z += 1
    return t,z

In [143]:
fun('KkAL')

(2, 1)

**Write a Python function that takes a list and returns a new list with unique elements of the first list.**

In [144]:
def uni(list):
    return set(list)

In [146]:
uni([4,5,5,7,7,7,8])

{4, 5, 7, 8}

**Write a Python function to multiply all the numbers in a list.**

In [1]:
def multy(num):    
    t=1
    for i in range(0,len(num)):
        t=t * num[i]
    return t

In [2]:
multy([1,5,3,4])

60

In [3]:
# second way
def mul(num):
    t=1
    for num in num:
        t= t*num
    return t

In [5]:
mul([1,5,3,4])

60

#### Write a Python function that checks whether a word or phrase is palindrome or not.

In [15]:
def pali(num):
    if num[:]==num[::-1]:
            return 'palindrome'
    elif num[:]!=num[::-1]:
            return 'non palindrome'

In [16]:
num='teet'
pali(num)

'palindrome'

In [20]:
num='text'
pali(num)

'non palindrome'

# Validation user input
### write a program whcih takes only 'digit' from user not string. So it should reapets inputing untill the user gives number not string.


In [26]:
def user_choice():
    
    # This original choice value can be anything that isn't an integer
    choice = 'wrong'
    
    # While the choice is not a digit, keep asking for input.
    while choice.isdigit() == False:
        
        # we shouldn't convert here, otherwise we get an error on a wrong input
        choice = input("Choose a number: ")
    
    # We can convert once the while loop above has confirmed we have a digit.
    return int(choice)

In [27]:
user_choice()

Choose a number: iuti
Choose a number: 5


5

In [29]:
'hello'.isdigit()

False

In [31]:
'5282'.isdigit()

True

### Now write a program whcih takes only 'digit' from user not string. So it should reapets inputing untill the user gives number not string. Moreover, it should reapeat inputing untill user provides digit whitin a range, here 0-10

In [1]:
def user_choice():
    
    #inituail
    choice ='WRONG'
    within_range = False
    
    # two conditions to check
    # digit or whitin range
    while choice.isdigit() == False or within_range == False:
        
    
    
        choice = input("Please enter a number (0-10): ")
        
        if choice.isdigit() == False:
            print("Sorry that is not a digit!")
            
        if choice.isdigit() == True:
            if int(choice) in range(0,10):
                within_range = True
            else:
                within_range = False
        
    
    return int(choice)

In [2]:
user_choice()

Please enter a number (0-10): 50
Please enter a number (0-10): 2


2

# enumerate()
### Enumerate allows you to keep a count as you iterate through an object. It does this by returning a tuple in the form (count,element).

In [3]:
lst = ['a','b','c']

for number,item in enumerate(lst):
    print(number)
    print(item)

0
a
1
b
2
c


In [4]:
for count,item in enumerate(lst):
    if count >= 2:
        break
    else:
        print(item)

a
b


### Use enumerate() and other skills to return a dictionary which has the values of the list as keys and the index as the value. You may assume that a value will only appear once in the given list.

In [15]:
def d_list(L):
    
    return {key:value for value,key in enumerate(L)}

In [16]:
d_list(['a','b','c','d'])

{'a': 0, 'b': 1, 'c': 2, 'd': 3}

### Use enumerate() and other skills from above to return the count of the number of items in the list whose value equals its index.


In [ ]:
def count_match_index(L):
   
    return len([num for count,num in enumerate(L) if num==count])

In [ ]:
count_match_index([0,2,2,1,5,5,6,10])

# complex() 
### returns a complex number with the value real + imag*1j or converts a string or number to a complex number.

In [6]:
# Create 2+3j
complex(2,3)

(2+3j)

# Reduce()
### The function reduce(function, sequence) ''continually'' (mohem, hei edame mide mesle derakht) applies the function to the sequence. It then returns a single value.

In [10]:
from functools import reduce
lst =[47,11,42,13]

In [11]:
#Find the maximum of a sequence (This already exists as max())
max_find = lambda a,b: a if (a > b) else b

In [12]:
#Find max
reduce(max_find,lst)

47

### Use map() to create a function which finds the length of  word

In [122]:
def fun(num):
    return len(num)

nums=('aha','jfjkhgk')
x=map(fun,nums)

In [123]:
print(map(fun,nums))

In [124]:
for i in x:
    print(i)

3
7


In [126]:
def fun(num):
    return len(num)

note to ','
nums=('aha',)
x=map(fun,nums)

In [127]:
print(x)

In [128]:
for i in x:
    print(i)

3


### Use map() to create a function which finds the length of each word in the phrase (broken by spaces) and return the values in a list.

def fun(num):
    a=num.split()
    b=[]
    for i in range(0,len(a)):
        b.append(a.count(a[i]))
    return b

#first try to chekc if the fun works fine
c=fun('num der der text alpha tex')
c

In [31]:
# now try with map method, note to ','
nums=('num der der text alpha tex',)
g=map(fun, nums)

In [32]:
for i in g:
    print(i)

[1, 2, 2, 1, 1, 1]


### Use reduce() to take a list of digits and return the number that they correspond to. For example, [1,2,3] corresponds to one-hundred-twenty-three.  <br>*Do not convert the ntegers to strings!* 

In [20]:
def fun(number):
    n=0
    for i in range(0,len(number)):
        number[i]=number[i]*(10**(len(number)-1-i))
        n+=number[i]
    return n

In [24]:
fun([5,2,3])

523

### Now try with reduce and lambda 

In [13]:
from functools import reduce
def fun(number):
    return reduce(lambda x,y: x*10+y,number)
# aval ru 2 ta  avali anjam mide mishe, 57,6,4 bad in 3 ta mishe 570+6=576, bad ru 576,4 anjam
# mide mishe 5760+4

In [14]:
fun([5,7,6,4])

5764

### Use filter() to return the words from a list of words which start with a target letter.